Transform API to unicode
ziima/python-openid pull request #4
Opened 2018-05-04 14:48 UTC by ziima

2018-05-04 15:21 UTC, tpazderka requested changes

2018-05-04 15:21 UTC, tpazderka commented on openid/kvform.py
> +        if not isinstance(k, six.text_type):
The order of operations should be reversed here. First, make sure to convert non string objects and then convert to text.

2018-05-04 15:21 UTC, tpazderka commented on openid/oidutil.py
> +    If input is text, it is returned as is.
or any other type...

2018-05-11 07:29 UTC, ziima commented on openid/kvform.py
> +        if not isinstance(k, six.text_type):
Fixed.

2018-05-11 07:30 UTC, ziima commented on openid/oidutil.py
> +    If input is text, it is returned as is.
That's not intended usage. I've added assert to warn about that.

2018-05-14 08:03 UTC, tpazderka approved these changes

2018-05-15 08:56 UTC, merged